# This config file for Travis CI
sudo: required
dist: trusty
services:
  - docker
cache: ccache
notifications:
  email:
    recipients:
      - levi.armstrong@swri.org
env:
  global:
    - ROS_DISTRO=kinetic
    - UPSTREAM_WORKSPACE=file
    - ROSINSTALL_FILENAME=dependencies.rosinstall
    - NOT_TEST_INSTALL=true
  matrix:
    - ROS_DISTRO=kinetic ROS_REPO=ros
    - ROS_DISTRO=kinetic ROS_REPO=ros-shadow-fixed
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - .industrial_ci/travis.sh

